### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by gmonteeeiro** [gmonteeeiro/vps-app-deployment#1]
## Cliente _- Electron (multiplataforma)_
- [ ] Configurações do aplicativo
   - [ ] IP do VPS
   - [ ] Porta
   - [ ] Senha de acesso do aplicativo
- [ ]  Adicionar aplicativos
   - [ ] Nome
   - [ ] Local do executável
   - [ ] Inicializar com o sistema? (sim/nao)
   - [ ] Padrão: Derrubar programa ao atualizar? (sim/nao)
- [ ]  Atualizar aplicativos
   - [ ] Derrubar programa ao atualizar (sim/nao)

## VPS _- NodeJs (multiplataforma)_
- [ ] UserInfo - Configurações
   - [ ] Porta
   - [ ] Senha para o cliente
   - [ ] Local para deixar os aplicativos
- [ ]  Aplicativos
   - [ ] Nome
   - [ ] Executável
   - [ ] Inicializar com o sistema? (sim/nao)
   - [ ] Padrão: Derrubar programa ao atualizar? (sim/nao)
